### ISSUE TITLE
Spaces in path to code location (4.4.3)

### ISSUE THREAD

**Issue by jamiewhths** [diffplug/matlabcontrol#18]
Related to issue #15 - spaces in paths to code location cause a URISyntaxException. Run on Windows 7 within an Eclipse application.

```
osgi> matlabcontrol.MatlabConnectionException: Support code location could not b
e determined. Could not convert URI location to file path.
URL Location: file:/C:/TEST PATH/configuration/org.eclipse.osgi/477/0/.cp/lib/ma
tconsolectl-4.4.3.jar
Code Source: (file:/C:/TEST PATH/configuration/org.eclipse.osgi/477/0/.cp/lib/ma
tconsolectl-4.4.3.jar <no signer certificates>)
Protection Domain: ProtectionDomain  (file:/C:/TEST PATH/configuration/org.eclip
se.osgi/477/0/.cp/lib/matconsolectl-4.4.3.jar <no signer certificates>)
 null
 <no principals>
 java.security.AllPermissionCollection@17a1763 (
 ("java.security.AllPermission" "<all permissions>" "<all actions>")
)
```

The issue occurs when generating a canonical file in Configuration#getSupportCodeLocation() at line 206: `File file = new File(url.toURI()).getCanonicalFile();` The conversion of the URL to URI (`url.toURI()`) throws an exception as spaces occur and are not encoded.

Playing around with different procedures for generating the canonical path was a one step forward, two steps back exercise. The only method that seemed to work with minimal change to the code was to create a URI via a URL string with spaces replaced by %20:
```
URI uri = new URI(url.toString().replace(" ", "%20"));
File file = new File(uri).getCanonicalFile();
```

A small test output using the above procedure shows this should work to solve the issue, at least in this instance:

```
TEST SCRIPT:
URL:  file:/C:/TEST PATH/configuration/org.eclipse.osgi/477/0/.cp/lib/matconsole
ctl-4.4.3.jar
URI (URL String, " " Replaced): file:/C:/TEST%20PATH/configuration/org.eclipse.o
sgi/477/0/.cp/lib/matconsolectl-4.4.3.jar
FILE (URI): C:\TEST PATH\configuration\org.eclipse.osgi\477\0\.cp\lib\matconsole
ctl-4.4.3.jar
CFILE: C:\TEST PATH\configuration\org.eclipse.osgi\477\0\.cp\lib\matconsolectl-4
.4.3.jar
ABSLPATH: C:\TEST PATH\configuration\org.eclipse.osgi\477\0\.cp\lib\matconsolect
l-4.4.3.jar
```

**Comment by nedtwigg** [comment]
Thanks for the detective work.  I implemented your suggestion in a slightly more general way in the commit above.  Do you mind testing this to confirm it meets your needs?  If it does, I'll release this as v4.4.4.

**Comment by jamiewhths** [comment]
So I had tried a similar approach during my own testing by trying to encode the URL via the URLEncoder class the same way. Unfortunately it doesn't solve the issue as it encodes it incorrectly for file paths (possibly because it uses a + for spaces, not sure exactly) which makes the string unreadable to the URL constructor causing it to throw a MalformedURLException.

```
matlabcontrol.MatlabConnectionException: Support code location could not be dete
rmined. Could not resolve canonical path.
URL Location: file:/C:/TEST PATH/configuration/org.eclipse.osgi/480/0/.cp/lib/ma
tconsolectl-master-4.4.4.jar
Code Source: (file:/C:/TEST PATH/configuration/org.eclipse.osgi/480/0/.cp/lib/ma
tconsolectl-master-4.4.4.jar <no signer certificates>)
Protection Domain: ProtectionDomain  (file:/C:/TEST PATH/configuration/org.eclip
se.osgi/480/0/.cp/lib/matconsolectl-master-4.4.4.jar <no signer certificates>)
 null
 <no principals>
 java.security.AllPermissionCollection@80b2e6 (
 ("java.security.AllPermission" "<all permissions>" "<all actions>")
)
```

```
Caused by: java.net.MalformedURLException: no protocol: file%3A%2FC%3A%2FTEST+PA
TH%2Fconfiguration%2Forg.eclipse.osgi%2F480%2F0%2F.cp%2Flib%2Fmatconsolectl-mast
er-4.4.4.jar
        at java.net.URL.<init>(Unknown Source)
        at java.net.URL.<init>(Unknown Source)
        at java.net.URL.<init>(Unknown Source)
        at matlabcontrol.Configuration.getSupportCodeLocation(Configuration.java
:208)
        ... 55 more
```

I had another look to see if there was an alternative way to do it more generally, and I think I have a potential solution. Rather than generating a file via a URI which requires problematic conversion from URL -> URI, generate the file by getting the URL path via the getPath() method - i.e. 
`File file = new File(url.getPath()).getCanonicalFile();`

I did a few quick tests which showed it could be done, output is below: 
```
URL:              file:/C:/TEST PATH/configuration/org.eclipse.osgi/480/0/.cp/lib/matconsolectl-master-4.4.4.jar
URL (toPath()):   /C:/TEST PATH/configuration/org.eclipse.osgi/480/0/.cp/lib/matconsolectl-master-4.4.4.jar
FILE:             /C:/TEST PATH/configuration/org.eclipse.osgi/480/0/.cp/lib/matconsolectl-master-4.4.4.jar
FILE (Canonical): /C:/TEST PATH/configuration/org.eclipse.osgi/480/0/.cp/lib/matconsolectl-master-4.4.4.jar
PATH (Absolute):  /C:/TEST PATH/configuration/org.eclipse.osgi/480/0/.cp/lib/matconsolectl-master-4.4.4.jar
```

I implemented this solution in a local fork of matconsolectl, which was then successful in loading code sources with spaces in their file path:


```java
Configuration.java (Lines 203-208):

//Convert from url to absolute path
try {
    // generate canonical file using URL path
    File file = new File(url.getPath()).getCanonicalFile();     
    if (file.exists()) {
        return file.getAbsolutePath();
...
```

**Comment by nedtwigg** [comment]
I think there's a tug-of-war happening between this issue and #15...

**Comment by jamiewhths** [comment]
Hmm yes it seems like it. Ironically this has been a problem with another plugin in our application... 

Only real suggestion I have to satisfy both issues might be to try the above approach, then if the `file.exists()` check fails, attempt to construct the file via the URI method. That should mean you can construct a file from whitespaced URL without a MalformedURLException being thrown, and then if the check fails you try the alternative method for encoded URLs:

```java
//Convert from url to absolute path
try {
    // generate canonical file using URL path
    File file = new File(url.getPath()).getCanonicalFile();     
    if (file.exists()) {
        return file.getAbsolutePath();
    }
    else {
        // generate canonical file using URI
        file = new File(url.toURI()).getCanonicalFile();
        if(file.exists()) {
            return file.getAbsolutePath();
        } else {
            ClassLoader loader = Configuration.class.getClassLoader();
            throw new MatlabConnectionException("Support code location was determined improperly." +
                    " Location does not exist.\n" +
                    "Location determined as: " + file.getAbsolutePath() + "\n" +
                    "File: " + file + "\n" +
                    "URL Location: " + url + "\n" +
                    "Code Source: " + codeSource + "\n" +
                    "Protection Domain: " + domain + "\n" +
                    "Class Loader: " + loader +
                    (loader == null ? "" : "\nClass Loader Class: " + loader.getClass()));
        }
}
```

**Comment by nedtwigg** [comment]
Great idea.  Published in v4.4.4.
